

  
h2-datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  platform: org.hibernate.dialect.H2Dialect
  username: sa
  password: sa
  driver-class-name: org.h2.Driver
   
 