
server: 
  servlet:
    context-path: /practise-api
  port: 8080
  
spring:
  profiles: 
    active: dev 
  jpa:
    show-sql: true 
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
       enabled: true
logging:
 level:
   org:
     hibernate: 
       SQL: debug
      

#http://localhost:8080/practise-api/h2-console

 
